### ISSUE TITLE
Please create a tag for this bundle

### ISSUE THREAD

**Issue by greg0ire** [touki653/FTPBundle#1]
or maybe create a `branch-alias` in `composer.json` ?

**Comment by touki653** [comment]
This bundle is still in DEV mode because it doesn't support all the ftp-wrapper functionnalities (only downloader and creator) which will be changed on the next ftp-wrapper version. This is why no tag have been created yet.

**Comment by greg0ire** [comment]
What about the other suggestion ?

**Comment by touki653** [comment]
I did a quick commit with the example given in the [composer documentation](https://getcomposer.org/doc/articles/aliases.md).
You should now be able to require `1.0.*` let me know if that's incorrect.

**Comment by greg0ire** [comment]
Great, I'll try rightaway

**Comment by greg0ire** [comment]
I think it won't work because of my minimum stability setting, but this works : `^1.0@dev`. Thanks a lot!
